routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset' => false]);
Route::resource('channel', 'ChannelController');
Route::post('sendMessage', 'ChatController@sendMessage')->name('sendMessage');
Route::get('/home', 'HomeController@index')->name('home');
Route::get('chat/{sid}', 'ChatController@index')->name('chat');
Route::get('/', function () {
  return redirect('/home');
});

app/Http/Controllers/ChannelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Redirect;

class ChannelController extends Controller
{
    //$this->get(env('TWILIO_SERVICES_SID_URL')) => returns the service 
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
        $this->service = $this->getBasicService($this->get(env('TWILIO_SERVICES_SID_URL')));
    }

    // returns the BasicService and all BasicChannels
    public function index()
    {
        $this->getAllChannels();
        return view('channel.index')->with([
            'service' => $this->service,
            'channels' => $this->channels
        ]);
    }

    //creates a new Channel
    public function store(Request $request)
    {
        $this->post(env('TWILIO_CHANNELS_URL'), [
            'ServiceSid' => env('TWILIO_SERVICES_SID'),
            'UniqueName' => $request['unique_name']
        ]);
        return Redirect()->route('channel.index');
    }

    //returns to the view where a Channel can be deleted
    public function show($sid)
    {
        return view('channel.delete')->with([
            'channel' => $this->getBasicChannel($this->get(env('TWILIO_CHANNELS_URL') . '/' . $sid)),
            'service' => $this->service
        ]);
    }

    //returns to the view where the Channel can be updated
    public function edit($sid)
    {
        return view('channel.update')->with([
            'channel' => $this->getBasicChannel($this->get(env('TWILIO_CHANNELS_URL') . '/' . $sid)),
            'service' => $this->service
        ]);
    }

    //updates a Channel (only UniqueName)
    public function update(Request $request, $sid)
    {
        $this->post(env('TWILIO_CHANNELS_URL') . '/' . $sid, ['UniqueName' => $request['unique_name']]);
        return Redirect()->route('channel.index');
    }

    //deletes a Channel
    public function destroy($sid)
    {
        $this->delete(env('TWILIO_CHANNELS_URL') . '/' . $sid);
        return Redirect()->route('channel.index');
    }
}

resources/views/channel/delete.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-5">
			<div class="card">
				{!! Form::model($channel, ['route' => ['channel.destroy', $channel['sid']], 'method' => 'delete']) !!}
					<div class="card-header">
						<h3>Deleting the Channel:</h3>
					</div>
					<div class="card-body">
						{!! Form::token() !!}
						<div class="form-group">
							{!! Form::label('unique_name', 'Name:') !!}
							{!! Form::text('unique_name', $channel['unique_name'], ['class' => 'form-control', 'disabled']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('sid', 'Sid Code:') !!}
							{!! Form::text('sid', $channel['sid'], ['class' => 'form-control', 'disabled']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('messages_count', 'Messages Count:') !!}
							{!! Form::text('messages_count', $channel['messages_count'], ['class' => 'form-control', 'disabled']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('members_count', 'Members Count:') !!}
							{!! Form::text('members_count', $channel['members_count'], ['class' => 'form-control', 'disabled']) !!}
						</div>
					</div>
					<div class="card-footer">
						{!! Form::submit('Delete', ['class' => 'btn btn-danger']) !!}
						{!! link_to_route('channel.index', 'Exit', [], ['class' => 'btn btn-primary']) !!}
					</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/channel/index.blade.php
@extends('layouts.app')

@section('style')
<style type="text/css">
    .fa-edit, .fa-times-circle, .fa-check-circle{
        text-align: center;
        text-decoration: none;
        color: black;
    }
    .fa-edit:hover, .fa-times-circle:hover, .fa-check-circle:hover{
        text-align: center;
        text-decoration: none;
        color: black;
        font-size: 20px;
    }
    .table{
        text-align: center;
    }
</style>
@endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <div class="card">
                {{ Form::open(['route' => 'channel.store', 'role' => 'form']) }}
                    <div class="card-header">
                        <h3>Create a New Channel</h3>
                    </div>
                    <div class="card-body">
                        {{ Form::token() }}
                        <div class="form-group">
                            {!! Form::label('unique_name', 'Name:') !!}
                            {!! Form::text('unique_name', '', ['class' => 'form-control', 'placeholder' => 'Name for the new channel']) !!}
                        </div>
                    </div>
                    <div class="card-footer">
                        {!! Form::submit('Save', ['class' => 'btn btn-success']) !!}
                    </div>
                {{ Form::close() }}
            </div>
        </div>
    </div>
    <br>
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-header">
                    <div class="float-left"><h3>Welcome to {{ $service['friendly_name'] }}</h3></div>
                    <div class="float-right"><h5>Channels: {{ count($channels) }}</h5></div>
                </div>
                <div class="card-body">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">Date Created</th>
                                <th scope="col">Date Updated</th>
                                <th scope="col">Messages Count</th>
                                <th scope="col">Members Count</th>
                                <th scope="col">Options</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($channels as $channel)
                                <tr>
                                    <th scope="row">{{ $channel['unique_name'] }}</th>
                                    <td>{{ $channel['date_created'] }}</td>
                                    <td>{{ $channel['date_updated'] }}</td>
                                    <td>{{ $channel['messages_count'] }}</td>
                                    <td>{{ $channel['members_count'] }}</td>
                                    <td>
                                        <a href="{{ route('channel.edit', $channel['sid']) }}" title="Edit"><i class="fas fa-edit"></i></a>
                                         - 
                                        <a href="{{ route('channel.show', $channel['sid']) }}" title="Delete"><i class="fas fa-times-circle"></i></a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/channel/update.blade.php
@extends('layouts.app')

@section('content')
<br>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-5">
			<div class="card">
				{!! Form::model($channel, ['route' => ['channel.update', $channel['sid']], 'method' => 'put']) !!}
					<div class="card-header">
						<h3>Editing the Channel</h3>
					</div>
					<div class="card-body">
						{!! Form::token() !!}
					 	<div class="form-group">
							{!! Form::label('unique_name', 'Name:') !!}
							{!! Form::text('unique_name', $channel['unique_name'], ['class' => 'form-control']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('sid', 'Sid Code:') !!}
							{!! Form::text('sid', $channel['sid'], ['class' => 'form-control', 'disabled']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('messages_count', 'Messages Count:') !!}
							{!! Form::text('messages_count', $channel['messages_count'], ['class' => 'form-control', 'disabled']) !!}
						</div>
						<div class="form-group">
							{!! Form::label('members_count', 'Members Count:') !!}
							{!! Form::text('members_count', $channel['members_count'], ['class' => 'form-control', 'disabled']) !!}
						</div>
					</div>
					<div class="card-footer">
						{!! Form::submit('Update', ['class' => 'btn btn-warning']) !!}
						{!! link_to_route('channel.index', 'Exit', [], ['class' => 'btn btn-primary']) !!}
					</div>
				{!! Form::close() !!}
			</div>
		</div>
	</div>
</div>
@endsection